FROM elixir:1.17-alpine

RUN apk add --no-cache build-base git nodejs npm

WORKDIR /app

ENV MIX_ENV=dev

RUN mix local.hex --force && mix local.rebar --force

COPY mix.exs mix.lock ./
RUN mix deps.get

COPY . .
RUN mix deps.compile

EXPOSE 4000

CMD ["mix", "phx.server"]
